dotnet pack ./src/Amazon.Core             -c Release -o ./release/Amazon.Core
dotnet pack ./src/Amazon.CloudWatch       -c Release -o ./release/Amazon.CloudWatch
dotnet pack ./src/Amazon.CodeBuild        -c Release -o ./release/Amazon.CodeBuild
dotnet pack ./src/Amazon.DynamoDb         -c Release -o ./release/Amazon.DynamoDb
dotnet pack ./src/Amazon.Ec2              -c Release -o ./release/Amazon.Ec2
dotnet pack ./src/Amazon.Elb              -c Release -o ./release/Amazon.Elb
dotnet pack ./src/Amazon.Kinesis          -c Release -o ./release/Amazon.Kinesis
dotnet pack ./src/Amazon.Kinesis.Firehose -c Release -o ./release/Amazon.Kinesis.Firehose
dotnet pack ./src/Amazon.Kms              -c Release -o ./release/Amazon.Kms
dotnet pack ./src/Amazon.Lambda           -c Release -o ./release/Amazon.Lambda
dotnet pack ./src/Amazon.Rekognition      -c Release -o ./release/Amazon.Rekognition
dotnet pack ./src/Amazon.Rds              -c Release -o ./release/Amazon.Rds
dotnet pack ./src/Amazon.Route53          -c Release -o ./release/Amazon.Route53
dotnet pack ./src/Amazon.S3               -c Release -o ./release/Amazon.S3
dotnet pack ./src/Amazon.Ses              -c Release -o ./release/Amazon.Ses
dotnet pack ./src/Amazon.Ses.Extensions   -c Release -o ./release/Amazon.Ses.Extensions
dotnet pack ./src/Amazon.Sns              -c Release -o ./release/Amazon.Sns
dotnet pack ./src/Amazon.Ssm              -c Release -o ./release/Amazon.Ssm
dotnet pack ./src/Amazon.Sts              -c Release -o ./release/Amazon.Sts
dotnet pack ./src/Amazon.Sqs              -c Release -o ./release/Amazon.Sqs
dotnet pack ./src/Wasabi                  -c Release -o ./release/Wasabi